### ISSUE TITLE
content script error: TypeError: el.addEventListener is not a function

### ISSUE THREAD

**Issue by hirohe** [antfu/vitesse-webext#39]
in this commit af4f35baa03db5758d586ee0fd7f3c9d432bfd83 and ahead, content script will throw error
before commit af4f35baa03db5758d586ee0fd7f3c9d432bfd83, content script is functional

seems the output codes `addEventListener` function is declare in global scope,
and other code will call `window.addEventListener`

![image](https://user-images.githubusercontent.com/14357567/135751419-5d6537ca-4021-46b5-8884-23e300263a6f.png)

**Comment by hirohe** [comment]
I try to lock `vite` version to `"2.5.10"` in newest commit's code 8d98f92901890bebaf06a340c6774f9b1697c6ff,
delete `node_modules` and run `pnpm i` and `npm run build`,
and content script is working normally

**Comment by tmkx** [comment]
Could you provide a minimum replication or a more clear and concise description of what the bug is?

**Comment by bhagyas** [comment]
The issue can be replicated upon running `pnpm start:chromium`

**Comment by tmkx** [comment]
caused by https://github.com/vitejs/vite/commit/06d86e4a2e90ca916a43d450bca1e6c28bc4bfe2 in https://github.com/vitejs/vite/compare/v2.6.0-beta.2...v2.6.0-beta.3.
